# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'верно.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Right(object):
    def setupUi(self, Right):
        Right.setObjectName("Right")
        Right.resize(333, 121)
        self.label = QtWidgets.QLabel(Right)
        self.label.setGeometry(QtCore.QRect(0, 0, 331, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Right)
        QtCore.QMetaObject.connectSlotsByName(Right)

    def retranslateUi(self, Right):
        _translate = QtCore.QCoreApplication.translate
        Right.setWindowTitle(_translate("Right", "АУК"))
        self.label.setText(_translate("Right", "Верно!"))
