# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'неверно.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wrong(object):
    def setupUi(self, Wrong):
        Wrong.setObjectName("Wrong")
        Wrong.resize(333, 121)
        self.label = QtWidgets.QLabel(Wrong)
        self.label.setGeometry(QtCore.QRect(0, 0, 331, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Wrong)
        QtCore.QMetaObject.connectSlotsByName(Wrong)

    def retranslateUi(self, Wrong):
        _translate = QtCore.QCoreApplication.translate
        Wrong.setWindowTitle(_translate("Wrong", "АУК"))
        self.label.setText(_translate("Wrong", "Неверно!"))
