# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'теория_26.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Teoria26Window(object):
    def setupUi(self, Teoria26Window):
        Teoria26Window.setObjectName("Teoria26Window")
        Teoria26Window.resize(1041, 682)
        Teoria26Window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Teoria26Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(211, 239, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_return26 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_return26.sizePolicy().hasHeightForWidth())
        self.btn_return26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_return26.setFont(font)
        self.btn_return26.setStyleSheet("background-color: rgb(211, 239, 255);\n"
"color: rgb(0, 0, 0);")
        self.btn_return26.setObjectName("btn_return26")
        self.horizontalLayout.addWidget(self.btn_return26)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_oglavlenie26 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btn_oglavlenie26.setFont(font)
        self.btn_oglavlenie26.setStyleSheet("background-color: rgb(211, 239, 255);\n"
"color: rgb(0, 0, 0);")
        self.btn_oglavlenie26.setObjectName("btn_oglavlenie26")
        self.horizontalLayout.addWidget(self.btn_oglavlenie26)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_glavnaya26 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_glavnaya26.setFont(font)
        self.btn_glavnaya26.setStyleSheet("background-color: rgb(211, 239, 255);\n"
"color: rgb(0, 0, 0);")
        self.btn_glavnaya26.setObjectName("btn_glavnaya26")
        self.horizontalLayout.addWidget(self.btn_glavnaya26)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btn_dalee26 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_dalee26.setFont(font)
        self.btn_dalee26.setStyleSheet("background-color: rgb(211, 239, 255);\n"
"color: rgb(0, 0, 0);")
        self.btn_dalee26.setObjectName("btn_dalee26")
        self.horizontalLayout.addWidget(self.btn_dalee26)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("background-color: rgb(191, 216, 230);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setStyleSheet("background-color: rgb(191, 216, 230);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 1)
        Teoria26Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Teoria26Window)
        self.statusbar.setObjectName("statusbar")
        Teoria26Window.setStatusBar(self.statusbar)

        self.retranslateUi(Teoria26Window)
        QtCore.QMetaObject.connectSlotsByName(Teoria26Window)

    def retranslateUi(self, Teoria26Window):
        _translate = QtCore.QCoreApplication.translate
        Teoria26Window.setWindowTitle(_translate("Teoria26Window", "АУК"))
        self.textBrowser.setHtml(_translate("Teoria26Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">3.1.3. Прекращение поступления питательной воды в котёл (уменьшение расхода питательной воды до установленного предела до 100 т/ч на нитку). Защита действует с выдержкой времени до 30 с.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">3.1.4. Повышение давления природного газа перед горелками до 1,0 кгс/см</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; vertical-align:super;\">2</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\"> (переведена на сигнал).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">3.1.5. Понижение давления среды перед встроенной задвижкой (рис. 17) до 200 кгс/см</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; vertical-align:super;\">2</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">. Защита действует с выдержкой времени до 180 с.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">3.1.6. Повышение давления среды перед встроенной задвижкой до 320 кгс/см</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; vertical-align:super;\">2</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">3.1.7. Понижение давления среды перед встроенной задвижкой во время пуска до установленного предела до 200 кг/см</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; vertical-align:super;\">2</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\"> (автоматический вывод при повышении давления в камере регулирующей ступени ЦВД 60 кгс/см</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; vertical-align:super;\">2</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">3.1.8. Понижение расхода пара через промежуточный пароперегреватель (уменьшение перепада давлений на всем пароперегревателе (рис. 18) до значения 0,05 кгс/см</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; vertical-align:super;\">2</span><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\"> соответствующего 20 % расходу пара). Защита действует с выдержкой времени до 20 с.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">3.1.9. Отключение электродвигателей обоих дымососов (или одного из них, если другой не работает).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">3.1.10. Отключение электродвигателей обоих дутьевых вентиляторов (или одного из них, если другой не работает).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Teoria26Window", "Защиты, действующие на останов котла"))
        self.btn_return26.setText(_translate("Teoria26Window", "Назад"))
        self.btn_oglavlenie26.setText(_translate("Teoria26Window", "Оглавление"))
        self.btn_glavnaya26.setText(_translate("Teoria26Window", "На главную"))
        self.btn_dalee26.setText(_translate("Teoria26Window", "Далее"))
